<?php
session_start();
require_once 'config/database.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit();
}

// Initialize messages
$success_message = '';
$error_message = '';

// Handle filter parameters
$project_filter = isset($_GET['project_filter']) ? (int)$_GET['project_filter'] : 0;
$status_filter = isset($_GET['status_filter']) ? $_GET['status_filter'] : '';
$date_from_filter = isset($_GET['date_from_filter']) ? $_GET['date_from_filter'] : '';
$date_to_filter = isset($_GET['date_to_filter']) ? $_GET['date_to_filter'] : '';

// Check for success message in session
if (isset($_SESSION['success_message'])) {
    $success_message = $_SESSION['success_message'];
    unset($_SESSION['success_message']); // Clear the message so it doesn't show again on refresh
}

// Handle form submission for new TEV claim
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['action'])) {
    if ($_POST['action'] == 'add') {
        try {
            $purpose = trim($_POST['purpose']);
            $amount = floatval($_POST['amount']);
            $project_id = !empty($_POST['project_id']) ? intval($_POST['project_id']) : null;
            $activity_id = !empty($_POST['activity_id']) ? intval($_POST['activity_id']) : null;
            $status = $_POST['status'];
            
            // Basic validation
            if (empty($purpose) || $amount <= 0 || empty($project_id) || empty($activity_id) || empty($status)) {
                throw new Exception("Please fill in all required fields with valid data.");
            }
            
            // Get user information
            $stmt = $pdo->prepare("SELECT full_name FROM users WHERE id = ?");
            $stmt->execute([$_SESSION['user_id']]);
            $user = $stmt->fetch();
            
            if (!$user) {
                throw new Exception("User information not found.");
            }
            
            // Set default department since it's not stored in users table
            $user['department'] = "DICT";  // Default department, you can modify this as needed
            
            // Get project title if project_id is provided
            $project_title = null;
            if ($project_id) {
                $stmt = $pdo->prepare("SELECT title FROM projects WHERE id = ?");
                $stmt->execute([$project_id]);
                $project = $stmt->fetch();
                $project_title = $project ? $project['title'] : null;
            }
            
            // Insert TEV claim (reference will be auto-generated by trigger)
            $stmt = $pdo->prepare("
                INSERT INTO tev_claims 
                (employee_name, department, claim_date, purpose, amount, status, project_id, project_title, activity_id, created_by)
                VALUES (?, ?, CURDATE(), ?, ?, ?, ?, ?, ?, ?)
            ");
            
            $stmt->execute([
                $user['full_name'],  // Fixed: Changed from 'fullname' to 'full_name'
                $user['department'],
                $purpose,
                $amount,
                $status,
                $project_id,
                $project_title,
                $activity_id,
                $_SESSION['user_id']
            ]);
            
            // Set success message in session and redirect to prevent form resubmission
            $_SESSION['success_message'] = "TEV claim submitted successfully!";
            header("Location: " . $_SERVER['PHP_SELF']);
            exit();
            
        } catch (Exception $e) {
            $error_message = "Error: " . $e->getMessage();
        }
    }
}

// Fetch projects for dropdown
try {
    // Updated query to match the actual status values in the database
    $stmt = $pdo->query("SELECT id, title FROM projects WHERE status IN ('In Progress', 'Not Started') ORDER BY title");
    $projects = $stmt->fetchAll();
    
    // Debug: Log projects to error log
    error_log("Projects found: " . count($projects));
    
    // Debug: Output projects to HTML comment for inspection
    echo "<!-- Projects: " . print_r($projects, true) . " -->";
    
} catch (Exception $e) {
    $error_message = "Error fetching projects: " . $e->getMessage();
    $projects = [];
    error_log($error_message);
    echo "<!-- Error: " . htmlspecialchars($e->getMessage()) . " -->";
}

// Fetch user's TEV claims with project and activity details
try {
    // Build base query with filters
    $params = [];
    $where = [];
    
    $base_query = "
        SELECT 
            tc.*, 
            p.title as project_title, 
            a.title as activity_title,
            a.start_date as activity_start_date,
            a.end_date as activity_end_date
        FROM tev_claims tc
        LEFT JOIN projects p ON tc.project_id = p.id
        LEFT JOIN activities a ON tc.activity_id = a.id
        WHERE tc.created_by = ?
    ";
    
    $params[] = $_SESSION['user_id'];
    
    // Add project filter
    if (!empty($project_filter)) {
        $where[] = 'tc.project_id = ?';
        $params[] = $project_filter;
    }
    
    // Add status filter
    if (!empty($status_filter)) {
        $where[] = 'LOWER(tc.status) = LOWER(?)';
        $params[] = $status_filter;
    }
    
    // Add date range filter
    if (!empty($date_from_filter)) {
        $where[] = 'DATE(tc.claim_date) >= ?';
        $params[] = $date_from_filter;
    }
    
    if (!empty($date_to_filter)) {
        $where[] = 'DATE(tc.claim_date) <= ?';
        $params[] = $date_to_filter;
    }
    
    // Combine WHERE clauses
    if (!empty($where)) {
        $base_query .= ' AND ' . implode(' AND ', $where);
    }
    
    $base_query .= " ORDER BY COALESCE(a.start_date, tc.claim_date) DESC, a.title ASC";
    
    $stmt = $pdo->prepare($base_query);
    $stmt->execute($params);
    $claims = $stmt->fetchAll();
} catch (Exception $e) {
    $error_message = "Error fetching TEV claims: " . $e->getMessage();
    $claims = [];
}

// Compute paid and unpaid aggregates for current user's claims
$paidCount = 0;
$unpaidCount = 0;
$paidTotal = 0.0;
$unpaidTotal = 0.0;

foreach ($claims as $c) {
    $amount = isset($c['amount']) ? floatval($c['amount']) : 0.0;
    if (isset($c['status']) && strtolower($c['status']) === 'paid') {
        $paidCount++;
        $paidTotal += $amount;
    } else {
        $unpaidCount++;
        $unpaidTotal += $amount;
    }
}

// Fetch projects for dropdown
try {
    // Updated query to match the actual status values in the database
    $stmt = $pdo->query("SELECT id, title FROM projects WHERE status IN ('In Progress', 'Not Started') ORDER BY title");
    $projects = $stmt->fetchAll();
    
    // Debug: Log projects to error log
    error_log("Projects found: " . count($projects));
    
    // Debug: Output projects to HTML comment for inspection
    echo "<!-- Projects: " . print_r($projects, true) . " -->";
    
} catch (Exception $e) {
    $error_message = "Error fetching projects: " . $e->getMessage();
    $projects = [];
    error_log($error_message);
    echo "<!-- Error: " . htmlspecialchars($e->getMessage()) . " -->";
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Personal Monitoring System - TEV Claims</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <style>
        :root {
            --primary-bg: #0f172a;
            --secondary-bg: #1e293b;
            --accent-color: #64ffda;
            --accent-secondary: #7c3aed;
            --text-primary: #f8fafc;
            --text-secondary: #94a3b8;
            --card-bg: #1e293b;
            --card-hover: #334155;
            --success-color: #10b981;
            --warning-color: #f59e0b;
            --danger-color: #ef4444;
            --border-color: #334155;
        }

        body {
            background-color: var(--primary-bg);
            color: var(--text-primary);
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            min-height: 100vh;
            overflow-x: hidden;
        }

        .main-content {
            padding: 2rem;
            margin-left: 350px;
            max-width: calc(100% - 350px);
            transition: all 0.3s ease;
        }
        
        @media (max-width: 1200px) {
            .main-content {
                margin-left: 0;
                max-width: 100%;
                padding: 1.5rem;
            }
        }

        /* Add responsive adjustments */
        @media (max-width: 992px) {
            .main-content {
                margin-left: 0;
                width: 100%;
                padding: 1rem;
                margin-top: 60px; /* Add space for mobile header */
            }
        }

        .card {
            background: var(--secondary-bg);
            border: 1px solid var(--border-color);
            border-radius: 16px;
            margin-bottom: 1.5rem;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
        }

        .card-header {
            background-color: var(--secondary-bg);
            border-bottom: 1px solid var(--border-color);
            padding: 1.25rem 1.5rem;
            border-top-left-radius: 16px !important;
            border-top-right-radius: 16px !important;
        }

        .card-body {
            padding: 1.5rem;
        }

        /* Table Styling */
        .table {
            color: var(--text-light);
            margin-bottom: 0;
            border-collapse: separate;
            border-spacing: 0;
        }

        /* Table Header Colors */
        .table th {
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.9rem;
            letter-spacing: 0.05em;
            color: var(--text-light);
            background-color: rgba(30, 41, 59, 0.9);
            border-bottom: 2px solid var(--accent-color);
            padding: 1.1rem 1.5rem;
            position: sticky;
            top: 0;
            z-index: 10;
            backdrop-filter: blur(10px);
            white-space: nowrap;
        }

        /* Table Cell Colors */
        .table td {
            padding: 1.25rem 1.5rem;
            vertical-align: middle;
            border-bottom: 1px solid var(--border-color);
            color: var(--text-light);
            background-color: var(--card-bg);
            transition: all 0.2s ease;
        }

        /* Hover effect for table rows */
        .table tbody tr:hover td {
            background-color: var(--card-hover);
            transform: translateX(2px);
        }

        /* Remove border from thead */
        .table thead th {
            border-top: none;
        }

        /* First and last cell in each row */
        .table td:first-child {
            border-left: 1px solid var(--border-color);
        }

        .table td:last-child {
            border-right: 1px solid var(--border-color);
        }

        /* Rounded corners for first and last row */
        .table tbody tr:first-child td:first-child {
            border-top-left-radius: 8px;
        }

        .table tbody tr:first-child td:last-child {
            border-top-right-radius: 8px;
        }

        .table tbody tr:last-child td:first-child {
            border-bottom-left-radius: 8px;
        }

        .table tbody tr:last-child td:last-child {
            border-bottom-right-radius: 8px;
        }

        /* Remove extra border on thead */
        .table thead th:first-child {
            border-top-left-radius: 8px;
        }

        .table thead th:last-child {
            border-top-right-radius: 8px;
        }

        /* Responsive table container */
        .table-container {
            max-height: calc(100vh - 600px);
            min-height: 62px;
            overflow-x: auto;
            -webkit-overflow-scrolling: touch;
            border-radius: 0 0 10px 10px;
        }

        /* Custom scrollbar */
        .table-container::-webkit-scrollbar {
            width: 8px;
            height: 8px;
        }

        .table-container::-webkit-scrollbar-track {
            background: rgba(255, 255, 255, 0.1);
            border-radius: 4px;
        }

        .table-container::-webkit-scrollbar-thumb {
            background: var(--accent-color);
            border-radius: 4px;
        }

        .table-container::-webkit-scrollbar-thumb:hover {
            background: #4dffd1;
        }

        /* Hover effects */
        .table tbody tr {
            transition: all 0.2s ease;
        }

        .table tbody tr:hover td {
            background-color: rgba(100, 255, 218, 0.05);
            transform: scale(1.01);
        }

        .table-hover tbody tr:hover {
            background-color: transparent;
        }

        .table-hover tbody tr:hover td {
            color: var(--accent-color);
        }

        @media (max-width: 992px) {
            .table-container {
                max-height: calc(100vh - 280px);
            }
            
            .table {
                width: 100%;
                margin-bottom: 1rem;
                display: block;
                overflow-x: auto;
                -webkit-overflow-scrolling: touch;
            }
        }

        /* Card styling */
        .card {
            background: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 16px;
            overflow: hidden;
        }

        /* Make sure the table takes full width */
        .table-responsive {
            width: 100%;
        }

        .btn-custom {
            background-color: var(--accent-color);
            color: #0f172a;
            border: none;
            font-weight: 600;
            padding: 0.5rem 1.25rem;
            border-radius: 6px;
            transition: all 0.2s;
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
        }

        .btn-custom:hover {
            background-color: #53e0c0;
            transform: translateY(-1px);
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
            color: #0f172a;
        }

        .badge {
            font-weight: 500;
            padding: 0.4em 0.8em;
            font-size: 0.8em;
            border-radius: 6px;
            text-transform: capitalize;
        }

        .badge-draft { background-color: #6c757d; }
        .badge-submitted { background-color: #0d6efd; }
        .badge-under_review { background-color: #0dcaf0; }
        .badge-approved { background-color: #198754; }
        .badge-rejected { background-color: #dc3545; }
        .badge-paid { background-color: #198754; }

        .form-control, .form-select {
            background-color: var(--secondary-bg);
            border: 1px solid var(--border-color);
            color: var(--text-primary);
            padding: 0.5rem 0.75rem;
        }

        .form-control:focus, .form-select:focus {
            background-color: var(--secondary-bg);
            color: var(--text-primary);
            border-color: var(--accent-color);
            box-shadow: 0 0 0 0.25rem rgba(100, 255, 218, 0.25);
        }

        .form-label {
            color: var(--text-secondary);
            margin-bottom: 0.5rem;
            font-weight: 500;
        }

        /* Reference number styling */
        .reference {
            font-family: 'Courier New', monospace;
            font-weight: 600;
            color: var(--accent-color);
        }

        /* Amount formatting */
        .amount {
            font-weight: 600;
            font-family: 'Courier New', monospace;
        }

        /* Status badges */
        .badge {
            padding: 0.4em 0.8em;
            font-weight: 500;
            text-transform: capitalize;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row h-100">
            <!-- Include Sidebar -->
            <?php include 'sidebar.php'; ?>
            
            <!-- Main Content -->
            <div class="main-content animate__animated animate__fadeIn">
                <div class="d-flex justify-content-between align-items-center mb-4 flex-wrap">
                    <h4 class="mb-0" style="font-weight: 700; letter-spacing: 1px; color: var(--accent-color); font-size: 1.5rem; text-transform: uppercase;">
                        <i class="bi bi-receipt me-2"></i>TEV Claims
                    </h4>
                    <button type="button" class="btn btn-custom" data-bs-toggle="modal" data-bs-target="#addTevClaimModal">
                        <i class="bi bi-plus-circle"></i> New TEV Claim
                    </button>
                </div>

                <!-- Filter Section -->
                <div class="card mb-4 animate__animated animate__fadeIn" id="filterSection">
                    <div class="card-body">
                        <form method="GET" class="row g-3 align-items-end">
                            <div class="col-md-3">
                                <label class="form-label small text-white mb-0">Project</label>
                                <select name="project_filter" class="form-select form-select-sm">
                                    <option value="">All Projects</option>
                                    <?php foreach ($projects as $project): ?>
                                        <option value="<?php echo $project['id']; ?>" <?php echo ($project_filter == $project['id']) ? 'selected' : ''; ?>>
                                            <?php echo htmlspecialchars($project['title']); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <label class="form-label small text-white mb-0">Status</label>
                                <select name="status_filter" class="form-select form-select-sm">
                                    <option value="">All</option>
                                    <option value="pending" <?php echo ($status_filter == 'pending') ? 'selected' : ''; ?>>Pending</option>
                                    <option value="approved" <?php echo ($status_filter == 'approved') ? 'selected' : ''; ?>>Approved</option>
                                    <option value="paid" <?php echo ($status_filter == 'paid') ? 'selected' : ''; ?>>Paid</option>
                                    <option value="rejected" <?php echo ($status_filter == 'rejected') ? 'selected' : ''; ?>>Rejected</option>
                                </select>
                            </div>
                            <div class="col-md-2">
                                <label class="form-label small text-white mb-0">From Date</label>
                                <input type="date" name="date_from_filter" class="form-control form-control-sm" value="<?php echo htmlspecialchars($date_from_filter); ?>">
                            </div>
                            <div class="col-md-2">
                                <label class="form-label small text-white mb-0">To Date</label>
                                <input type="date" name="date_to_filter" class="form-control form-control-sm" value="<?php echo htmlspecialchars($date_to_filter); ?>">
                            </div>
                            <div class="col-md-3 d-flex align-items-end justify-content-end">
                                <div class="d-flex gap-2 w-100">
                                    <button type="submit" class="btn btn-custom flex-fill">
                                        <i class="bi bi-funnel"></i> Filter
                                    </button>
                                    <a href="tev_claims.php" class="btn btn-outline-light flex-fill">
                                        <i class="bi bi-x-circle"></i> Clear
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Success message will be shown via JavaScript -->
                <div id="successAlert" class="alert alert-success animate__animated animate__fadeIn d-none" role="alert">
                    <i class="bi bi-check-circle me-2"></i>
                    <span id="successMessage"></span>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

                <?php if ($error_message): ?>
                    <div class="alert alert-danger animate__animated animate__fadeIn"><?php echo $error_message; ?></div>
                <?php endif; ?>

                <!-- Summary Cards -->
                <div class="row g-3 mb-4">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="card h-100" style="border-left: 4px solid var(--success-color);">
                            <div class="card-body d-flex align-items-center justify-content-between">
                                <div>
                                    <div class="text-white fw-bold" style="font-size: 0.95rem; text-transform: uppercase; letter-spacing: 0.03em;">Paid</div>
                                    <div class="h4 mb-0" style="color: var(--text-primary);">₱<?php echo number_format($paidTotal, 2); ?></div>
                                    <div class="small" style="color: var(--text-secondary);"><?php echo $paidCount; ?> claim(s)</div>
                                </div>
                                <div class="rounded-circle d-flex align-items-center justify-content-center" style="width:44px;height:44px;background: rgba(16, 185, 129, 0.15); color: var(--success-color);">
                                    <i class="bi bi-check2-circle"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="card h-100" style="border-left: 4px solid var(--warning-color);">
                            <div class="card-body d-flex align-items-center justify-content-between">
                                <div>
                                    <div class="text-white fw-bold" style="font-size: 0.95rem; text-transform: uppercase; letter-spacing: 0.03em;">Unpaid</div>
                                    <div class="h4 mb-0" style="color: var(--text-primary);">₱<?php echo number_format($unpaidTotal, 2); ?></div>
                                    <div class="small" style="color: var(--text-secondary);"><?php echo $unpaidCount; ?> claim(s)</div>
                                </div>
                                <div class="rounded-circle d-flex align-items-center justify-content-center" style="width:44px;height:44px;background: rgba(245, 158, 11, 0.15); color: var(--warning-color);">
                                    <i class="bi bi-hourglass-split"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card animate__animated animate__fadeInUp">
                    <div class="card-body p-0">
                        <div class="table-responsive table-container" style="max-height: 70vh; overflow-y: auto;">
                            <table class="table table-hover mb-0">
                                <thead>
                                    <tr>
                                        <th>Project
                                            <?php if ($project_filter): ?>
                                                <span class="badge bg-info ms-1">Filtered</span>
                                            <?php endif; ?>
                                        </th>
                                        <th>Activity</th>
                                        <th>Google Drive</th>
                                        <th>Activity Date</th>
                                        <th>Purpose</th>
                                        <th class="text-end">Amount</th>
                                        <th>Status
                                            <?php if ($status_filter): ?>
                                                <span class="badge bg-info ms-1"><?php echo ucfirst(htmlspecialchars($status_filter)); ?></span>
                                            <?php endif; ?>
                                        </th>
                                        <th class="text-end">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if (empty($claims)): ?>
                                        <tr>
                                            <td colspan="7" class="text-center py-4">
                                                <div class="d-flex flex-column align-items-center">
                                                    <i class="bi bi-receipt text-muted mb-2" style="font-size: 2rem;"></i>
                                                    <p class="text-muted mb-0">No TEV claims found</p>
                                                    <button class="btn btn-sm btn-outline-primary mt-2" 
                                                            data-bs-toggle="modal" data-bs-target="#addTevClaimModal">
                                                        <i class="bi bi-plus-circle"></i> Create Your First Claim
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php else: ?>
                                        <?php foreach ($claims as $claim): 
                                            $statusClass = 'badge-' . str_replace(' ', '-', strtolower($claim['status']));
                                        ?>
                                            <tr class="fade-in" data-claim-id="<?php echo $claim['id']; ?>">
                                                <td data-label="Project">
                                                    <?php echo $claim['project_title'] ? htmlspecialchars($claim['project_title']) : '<span class="text-muted">N/A</span>'; ?>
                                                </td>
                                                <td data-label="Activity">
                                                    <span class="activity-name"><?php echo htmlspecialchars($claim['activity_title'] ?? 'N/A'); ?></span>
                                                </td>
                                                <td data-label="Google Drive">
                                                    <?php if (!empty($claim['google_drive_link'])): ?>
                                                        <a href="<?php echo htmlspecialchars($claim['google_drive_link']); ?>" target="_blank" class="btn btn-sm btn-outline-primary">
                                                            <i class="bi bi-google-drive"></i> View
                                                        </a>
                                                    <?php else: ?>
                                                        <span class="text-muted">No link</span>
                                                    <?php endif; ?>
                                                </td>
                                                <td data-label="Activity Date">
                                                    <?php 
                                                    if (!empty($claim['activity_start_date']) && !empty($claim['activity_end_date'])) {
                                                        $start = date('M d', strtotime($claim['activity_start_date']));
                                                        $end = date('d, Y', strtotime($claim['activity_end_date']));
                                                        echo $start . ' - ' . $end;
                                                    } else {
                                                        echo date('M d, Y', strtotime($claim['claim_date']));
                                                    }
                                                    ?>
                                                </td>
                                                <td data-label="Purpose">
                                                    <?php echo htmlspecialchars(mb_strimwidth($claim['purpose'], 0, 50, '...')); ?>
                                                </td>
                                                <td data-label="Amount" class="text-end amount">
                                                    ₱<?php echo number_format($claim['amount'], 2); ?>
                                                </td>
                                                <td data-label="Status">
                                                    <span class="badge <?php echo $statusClass; ?>">
                                                        <?php 
                                                        if (strtolower($claim['status']) === 'paid' && !empty($claim['payment_date'])) {
                                                            echo 'Paid on ' . date('M d, Y', strtotime($claim['payment_date']));
                                                        } else {
                                                            echo htmlspecialchars(ucfirst($claim['status']));
                                                        }
                                                        ?>
                                                    </span>
                                                </td>
                                                <td data-label="Actions" class="text-end">
                                                    <div class="btn-group" role="group">
                                                        <!-- Mark as Paid Button (only show if not already paid) -->
                                                        <?php if ($claim['status'] !== 'Paid'): ?>
                                                        <button type="button" class="btn btn-sm btn-success mark-as-paid" 
                                                                data-id="<?php echo $claim['id']; ?>"
                                                                data-amount="<?php echo htmlspecialchars($claim['amount']); ?>"
                                                                data-bs-toggle="tooltip" 
                                                                title="Mark as Paid">
                                                            <i class="bi bi-cash-coin"></i>
                                                        </button>
                                                        <?php endif; ?>
                                                        
                                                        <!-- Always show Edit Button -->
                                                        <a href="edit_tev_claim.php?id=<?php echo $claim['id']; ?>" 
                                                           class="btn btn-sm btn-outline-warning edit-claim"
                                                           data-id="<?php echo $claim['id']; ?>"
                                                           data-bs-toggle="tooltip" 
                                                           title="Edit">
                                                                <i class="bi bi-pencil"></i>
                                                        </a>
                                                        
                                                        <!-- Always show Delete Button -->
                                                        <button class="btn btn-sm btn-outline-danger delete-claim" 
                                                                data-id="<?php echo $claim['id']; ?>"
                                                                data-bs-toggle="tooltip" 
                                                                title="Delete">
                                                                <i class="bi bi-trash"></i>
                                                        </button>
                                                        
                                                        <!-- Always show View Button -->
                                                        <button class="btn btn-sm btn-outline-primary view-claim" 
                                                                data-id="<?php echo $claim['id']; ?>"
                                                                data-bs-toggle="tooltip" 
                                                                title="View Details">
                                                                <i class="bi bi-eye"></i>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <?php if (!empty($claims)): ?>
                        <div class="card-footer bg-secondary bg-opacity-10 d-flex justify-content-between align-items-center">
                            <div class="small" style="color: white !important;">
                                Showing <span id="showingCount" style="color: white !important;"><?php echo count($claims); ?></span> of 
                                <span id="totalCount"><?php echo count($claims); ?></span> claims
                            </div>
                            <nav aria-label="Page navigation">
                                <ul class="pagination pagination-sm mb-0">
                                    <li class="page-item disabled">
                                        <a class="page-link bg-secondary border-secondary text-white" href="#" tabindex="-1">
                                            <i class="bi bi-chevron-left"></i>
                                        </a>
                                    </li>
                                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item">
                                        <a class="page-link bg-secondary border-secondary text-white" href="#">
                                            <i class="bi bi-chevron-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <!-- Mark as Paid Modal -->
    <div class="modal fade" id="markAsPaidModal" tabindex="-1" aria-labelledby="markAsPaidModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="markAsPaidModalLabel">Mark as Paid</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="markAsPaidForm">
                    <div class="modal-body">
                        <input type="hidden" id="mark_paid_claim_id" name="claim_id">
                        <div class="mb-3">
                            <label for="payment_date" class="form-label">Payment Date</label>
                            <input type="date" class="form-control" id="payment_date" name="payment_date" required>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="form-label">Amount Paid</label>
                            <div class="input-group">
                                <span class="input-group-text">₱</span>
                                <input type="number" class="form-control" id="amount" name="amount" step="0.01" min="0.01" required>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-success">
                            <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                            <span class="btn-text">Mark as Paid</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Add TEV Claim Modal -->
    <div class="modal fade" id="addTevClaimModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">New TEV Claim</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <form id="tevClaimForm" method="POST" action="">
                    <input type="hidden" name="action" value="add">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="project_id" class="form-label">Project <span class="text-danger">*</span></label>
                            <select class="form-select" id="project_id" name="project_id" required>
                                <option value="">Select Project</option>
                                <?php if (!empty($projects)): ?>
                                    <?php foreach ($projects as $project): ?>
                                        <option value="<?= $project['id'] ?>"><?= htmlspecialchars($project['title']) ?></option>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <option value="">No projects available</option>
                                <?php endif; ?>
                            </select>
                        </div>
                        
                        <div class="mb-3">
                            <label for="activity_id" class="form-label">Activity <span class="text-danger">*</span></label>
                            <select class="form-select" id="activity_id" name="activity_id" required disabled>
                                <option value="">Select Activity</option>
                            </select>
                        </div>
                        
                        <div class="mb-3">
                            <label for="amount" class="form-label">Amount <span class="text-danger">*</span></label>
                            <div class="input-group">
                                <span class="input-group-text">₱</span>
                                <input type="number" class="form-control" id="amount" name="amount" 
                                       step="0.01" min="0.01" required placeholder="0.00">
                            </div>
                        </div>
                        
                        <div class="mb-3">
                            <label for="google_drive_link" class="form-label">Google Drive Link</label>
                            <input type="url" class="form-control" id="google_drive_link" name="google_drive_link" 
                                   placeholder="https://drive.google.com/...">
                            <div class="form-text">Optional: Link to supporting documents in Google Drive</div>
                        </div>
                        
                        <div class="mb-3">
                            <label for="status" class="form-label">Status <span class="text-danger">*</span></label>
                            <select class="form-select" id="status" name="status" required>
                                <option value="Draft">Draft</option>
                                <option value="For Review">For Review</option>
                                <option value="Approved">Approved</option>
                                <option value="Rejected">Rejected</option>
                                <option value="Paid">Paid</option>
                            </select>
                        </div>
                        
                        <div class="mb-3">
                            <label for="purpose" class="form-label">Purpose/Description <span class="text-danger">*</span></label>
                            <textarea class="form-control" id="purpose" name="purpose" rows="5" required 
                                    placeholder="Enter purpose or description of the claim"></textarea>
                        </div>
                        
                        <div class="alert alert-info mb-0">
                            <i class="bi bi-info-circle me-2"></i>
                            The status will be set to "Draft" by default. You can submit it for review later.
                        </div>
                        
                        <div class="d-flex justify-content-end mt-4">
                            <button type="button" class="btn btn-secondary me-2" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">
                                <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                                <i class="bi bi-save me-1"></i> Save as Draft
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Edit TEV Claim Modal -->
    <div class="modal fade" id="editTevClaimModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edit TEV Claim</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <form id="editTevClaimForm" method="POST" action="">
                    <input type="hidden" name="action" value="edit">
                    <input type="hidden" name="claim_id" id="edit_claim_id" value="">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="edit_project_id" class="form-label">Project <span class="text-danger">*</span></label>
                            <select class="form-select" id="edit_project_id" name="project_id" required>
                                <option value="">Select Project</option>
                                <?php if (!empty($projects)): ?>
                                    <?php foreach ($projects as $project): ?>
                                        <option value="<?= $project['id'] ?>"><?= htmlspecialchars($project['title']) ?></option>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <option value="">No projects available</option>
                                <?php endif; ?>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="edit_activity_id" class="form-label">Activity <span class="text-danger">*</span></label>
                            <select class="form-select" id="edit_activity_id" name="activity_id" required disabled>
                                <option value="">Select Activity</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="edit_amount" class="form-label">Amount <span class="text-danger">*</span></label>
                            <div class="input-group">
                                <span class="input-group-text">₱</span>
                                <input type="number" class="form-control" id="edit_amount" name="amount" 
                                       step="0.01" min="0.01" required>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="edit_google_drive_link" class="form-label">Google Drive Link</label>
                            <input type="url" class="form-control" id="edit_google_drive_link" name="google_drive_link" 
                                   placeholder="https://drive.google.com/...">
                            <div class="form-text">Optional: Link to supporting documents in Google Drive</div>
                        </div>
                        <div class="mb-3">
                            <label for="edit_status" class="form-label">Status <span class="text-danger">*</span></label>
                            <select class="form-select" id="edit_status" name="status" required>
                                <option value="Draft">Draft</option>
                                <option value="For Review">For Review</option>
                                <option value="Approved">Approved</option>
                                <option value="Rejected">Rejected</option>
                                <option value="Paid">Paid</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="edit_purpose" class="form-label">Purpose/Description <span class="text-danger">*</span></label>
                            <textarea class="form-control" id="edit_purpose" name="purpose" rows="5" required></textarea>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-4">
                            <button type="button" class="btn btn-danger" id="deleteClaimBtn">
                                <i class="bi bi-trash me-1"></i> Delete
                            </button>
                            <div>
                                <button type="button" class="btn btn-secondary me-2" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary">
                                    <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                                    <i class="bi bi-save me-1"></i> Save Changes
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- View TEV Claim Modal -->
    <div class="modal fade" id="viewTevClaimModal" tabindex="-1" aria-labelledby="viewTevClaimModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content bg-dark">
                <div class="modal-header border-secondary">
                    <h5 class="modal-title text-white" id="viewTevClaimModalLabel">TEV Claim Details</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-white">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <div class="mb-4">
                                <label class="form-label text-white-50 mb-1">Reference Number</label>
                                <div id="view-reference" class="fw-medium text-white">TEV-2023-00001</div>
                            </div>
                            
                            <div class="mb-4">
                                <label class="form-label text-white-50 mb-1">Status</label>
                                <div>
                                    <span id="view-status" class="badge bg-primary text-white">Draft</span>
                                </div>
                            </div>
                            
                            <div>
                                <label class="form-label text-white-50 mb-1">Date Filed</label>
                                <div id="view-date" class="fw-medium text-white"><?php echo date('M d, Y'); ?></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-4">
                                <label class="form-label text-white-50 mb-1">Amount</label>
                                <div id="view-amount" class="h4 text-white fw-bold">₱0.00</div>
                            </div>
                            
                            <div class="mb-3">
                                <label class="form-label text-white-50 mb-1">Project</label>
                                <div id="view-project" class="fw-medium text-white">N/A</div>
                            </div>
                            
                            <div>
                                <label class="form-label text-white-50 mb-1">Activity</label>
                                <div id="view-activity" class="fw-medium text-white">N/A</div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mb-0">
                        <label class="form-label text-white-50 mb-2">Purpose/Description</label>
                        <div id="view-purpose" class="border border-secondary rounded p-3 bg-dark">
                            <div class="text-white">No description provided.</div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // Function to show success message
        function showSuccessMessage(message) {
            const successAlert = document.getElementById('successAlert');
            const successMessage = document.getElementById('successMessage');
            if (successAlert && successMessage) {
                successMessage.textContent = message;
                successAlert.classList.remove('d-none');
                // Auto-hide after 5 seconds
                setTimeout(() => {
                    successAlert.classList.add('d-none');
                }, 5000);
            }
        }

        // Initialize tooltips
        document.addEventListener('DOMContentLoaded', function() {
            // Ensure Google Drive Link is blank when opening the New TEV Claim modal
            const addTevClaimModalEl = document.getElementById('addTevClaimModal');
            if (addTevClaimModalEl) {
                addTevClaimModalEl.addEventListener('show.bs.modal', function () {
                    const addForm = document.getElementById('tevClaimForm');
                    if (addForm) {
                        addForm.reset();
                    }
                    const gdriveInput = document.getElementById('google_drive_link');
                    if (gdriveInput) {
                        gdriveInput.value = '';
                    }
                });
            }
            // Handle add form submission
            document.getElementById('tevClaimForm')?.addEventListener('submit', function(e) {
                e.preventDefault();
                
                const formData = new FormData(this);
                // Ensure google_drive_link is included in the form data
                const googleDriveLink = document.getElementById('google_drive_link')?.value || '';
                formData.set('google_drive_link', googleDriveLink);
                
                const submitButton = this.querySelector('button[type="submit"]');
                const originalHTML = submitButton.innerHTML;
                
                // Show loading state
                submitButton.disabled = true;
                submitButton.querySelector('.spinner-border').classList.remove('d-none');
                submitButton.querySelector('i').classList.add('d-none');
                
                // Send the add request
                fetch('save_tev_claim.php', {
                    method: 'POST',
                    body: formData
                })
                .then(response => {
                    // First, check if the response is JSON
                    const contentType = response.headers.get('content-type');
                    if (!contentType || !contentType.includes('application/json')) {
                        return response.text().then(text => {
                            console.error('Expected JSON but got:', text);
                            throw new Error('Server returned non-JSON response');
                        });
                    }
                    return response.json().catch(() => {
                        throw new Error('Invalid JSON response from server');
                    });
                })
                .then(data => {
                    if (data.success) {
                        // Show success message and reload the page
                        showSuccessMessage('TEV claim added successfully!');
                        // Reload after a short delay to show the message
                        setTimeout(() => window.location.reload(), 1000);
                    } else {
                        throw new Error(data.message || 'Failed to add TEV claim');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert('Error: ' + (error.message || 'Failed to add TEV claim'));
                })
                .finally(() => {
                    // Reset button state
                    submitButton.disabled = false;
                    submitButton.querySelector('.spinner-border').classList.add('d-none');
                    submitButton.querySelector('i').classList.remove('d-none');
                });
            });
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
            var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl);
            });

            // Function to handle activity selection (keep Google Drive Link blank for new claims)
            function handleActivitySelection(activitySelect, googleDriveInput) {
                if (!activitySelect || !googleDriveInput) return;
                // Always keep blank when creating a new TEV claim
                googleDriveInput.value = '';
            }

            // Handle project selection change
            const projectSelect = document.getElementById('project_id');
            const activitySelect = document.getElementById('activity_id');
            const googleDriveLinkInput = document.getElementById('google_drive_link');

            if (projectSelect && activitySelect) {
                // Handle activity selection change
                activitySelect.addEventListener('change', function() {
                    if (googleDriveLinkInput) {
                        handleActivitySelection(this, googleDriveLinkInput);
                    }
                });
                
                projectSelect.addEventListener('change', function() {
                    const projectId = this.value;
                    
                    // Reset and disable activity select
                    activitySelect.innerHTML = '<option value="">-- Select Activity --</option>';
                    activitySelect.disabled = true;
                    // Also clear Google Drive link on project change
                    if (googleDriveLinkInput) {
                        googleDriveLinkInput.value = '';
                    }
                    
                    if (projectId) {
                        // Fetch activities for the selected project
                        fetch(`get_activities.php?project_id=${projectId}`)
                            .then(response => response.json())
                            .then(data => {
                                if (data.success && data.activities.length > 0) {
                                    // Add activities to the select with status and dates
                                    data.activities.forEach(activity => {
                                        const option = document.createElement('option');
                                        option.value = activity.id;
                                        
                                        // Format dates for display
                                        const startDate = activity.start_date ? new Date(activity.start_date).toLocaleDateString() : 'N/A';
                                        const endDate = activity.end_date ? new Date(activity.end_date).toLocaleDateString() : 'N/A';
                                        
                                        // Create display text with status and dates
                                        option.textContent = `${activity.title} (${activity.status_display} - ${startDate} to ${endDate})`;
                                        
                                        // Add data attributes for reference if needed
                                        option.dataset.status = activity.status_display;
                                        option.dataset.startDate = activity.start_date;
                                        option.dataset.endDate = activity.end_date;
                                        option.dataset.googleDriveLink = activity.google_drive_link || '';
                                        
                                        activitySelect.appendChild(option);
                                    });
                                    activitySelect.disabled = false;
                                } else {
                                    activitySelect.innerHTML = '<option value="">No activities found</option>';
                                }
                            })
                            .catch(error => {
                                console.error('Error fetching activities:', error);
                                activitySelect.innerHTML = '<option value="">Error loading activities</option>';
                            });
                    }
                });
            }

            // Handle view claim button clicks
            document.querySelectorAll('.view-claim').forEach(button => {
                button.addEventListener('click', function(e) {
                    e.preventDefault();
                    const claimId = this.getAttribute('data-id');
                    if (!claimId) return;
                    
                    // Show loading state
                    const viewButton = this;
                    const originalHTML = viewButton.innerHTML;
                    viewButton.disabled = true;
                    viewButton.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...';
                    
                    fetch(`get_tev_claim.php?id=${claimId}`)
                        .then(response => response.json())
                        .then(data => {
                            // Reset button state
                            viewButton.innerHTML = originalHTML;
                            viewButton.disabled = false;
                            
                            if (data.success && data.data) {
                                const claim = data.data;
                                // Populate the view modal with claim data
                                document.getElementById('view-reference').textContent = claim.claim_reference || 'N/A';
                                document.getElementById('view-date').textContent = claim.claim_date ? new Date(claim.claim_date).toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }) : 'N/A';
                                document.getElementById('view-purpose').textContent = claim.purpose || 'No description';
                                document.getElementById('view-project').textContent = claim.project_title || 'N/A';
                                document.getElementById('view-activity').textContent = claim.activity_title || 'N/A';
                                document.getElementById('view-amount').textContent = claim.amount ? '₱' + parseFloat(claim.amount).toFixed(2) : '₱0.00';
                                
                                // Update status badge
                                const statusBadge = document.getElementById('view-status');
                                statusBadge.textContent = claim.status ? claim.status.replace('_', ' ') : 'N/A';
                                statusBadge.className = 'badge ' + getStatusClass(claim.status || '');
                                
                                // Show the view modal
                                const viewModal = new bootstrap.Modal(document.getElementById('viewTevClaimModal'));
                                viewModal.show();
                            } else {
                                throw new Error(data.message || 'Failed to load claim details');
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                            viewButton.innerHTML = originalHTML;
                            viewButton.disabled = false;
                            alert('Error: ' + (error.message || 'Failed to load claim details'));
                        });
                });
            });

            // Edit claim - Load data into modal
            document.querySelectorAll('.edit-claim').forEach(button => {
                button.addEventListener('click', function(e) {
                    e.preventDefault();
                    const claimId = this.getAttribute('data-id');
                    if (!claimId) return;
                    
                    // Show loading state
                    const editButton = this;
                    const originalHTML = editButton.innerHTML;
                    editButton.disabled = true;
                    editButton.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...';
                    
                    // Fetch claim data
                    fetch(`get_tev_claim.php?id=${claimId}`)
                        .then(response => {
                            if (!response.ok) {
                                return response.text().then(text => {
                                    console.error('Server response not OK. Status:', response.status, 'Response:', text);
                                    throw new Error(`HTTP error! status: ${response.status}`);
                                });
                            }
                            return response.text().then(text => {
                                try {
                                    return JSON.parse(text);
                                } catch (e) {
                                    console.error('Failed to parse JSON:', text);
                                    throw new Error('Invalid JSON response from server');
                                }
                            });
                        })
                        .then(data => {
                            // Reset button state
                            editButton.innerHTML = originalHTML;
                            editButton.disabled = false;
                            
                            if (data.success && data.data) {
                                const claim = data.data;
                                
                                // Populate the edit form with claim data
                                const form = document.getElementById('editTevClaimForm');
                                form.querySelector('input[name="claim_id"]').value = data.data.id;
                                
                                // Set project ID and trigger change event to load activities
                                const projectSelect = document.getElementById('edit_project_id');
                                if (projectSelect && data.data.project_id) {
                                    projectSelect.value = data.data.project_id;
                                    
                                    // Create and dispatch change event to load activities
                                    const event = new Event('change');
                                    projectSelect.dispatchEvent(event);
                                }
                                
                                // Set other form fields
                                const googleDriveLink = data.data.google_drive_link || data.data.google_drive_link || '';
                                const googleDriveInput = document.getElementById('edit_google_drive_link');
                                if (googleDriveInput) {
                                    googleDriveInput.value = googleDriveLink;
                                }
                                if (data.data.purpose) {
                                    document.getElementById('edit_purpose').value = data.data.purpose;
                                }
                                if (data.data.amount) {
                                    document.getElementById('edit_amount').value = data.data.amount;
                                }
                                if (data.data.status) {
                                    document.getElementById('edit_status').value = data.data.status;
                                }
                                
                                // Enable and clear activity dropdown
                                const activitySelect = document.getElementById('edit_activity_id');
                                activitySelect.disabled = false;
                                activitySelect.innerHTML = '<option value="">-- Select Activity --</option>';
                                
                                // Show the edit modal
                                const editModal = new bootstrap.Modal(document.getElementById('editTevClaimModal'));
                                editModal.show();
                                
                                // After a short delay to ensure the modal is shown, set the activity
                                setTimeout(() => {
                                    if (data.data.activity_id) {
                                        // Set the activity after the project's activities are loaded
                                        const activitySelect = document.getElementById('edit_activity_id');
                                        if (activitySelect) {
                                            // Set the activity ID
                                            activitySelect.value = data.data.activity_id;
                                            
                                            // If the activity has a Google Drive link, update it
                                            // Only override if the selected activity doesn't have its own link
                                            const selectedOption = activitySelect.options[activitySelect.selectedIndex];
                                            const googleDriveInput = document.getElementById('edit_google_drive_link');
                                            
                                            if (googleDriveInput) {
                                                const hasActivityDriveLink = selectedOption && selectedOption.dataset.googleDriveLink;
                                                if (!hasActivityDriveLink && data.data.google_drive_link) {
                                                    googleDriveInput.value = data.data.google_drive_link;
                                                } else if (hasActivityDriveLink) {
                                                    googleDriveInput.value = selectedOption.dataset.googleDriveLink;
                                                }
                                            }
                                        }
                                    }
                                }, 500);
                            } else {
                                throw new Error(data.message || 'Failed to load claim data');
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                            editButton.innerHTML = originalHTML;
                            editButton.disabled = false;
                });
            });
            
            // Handle edit form submission
            document.getElementById('editTevClaimForm')?.addEventListener('submit', function(e) {
                e.preventDefault();
                
                const formData = new FormData(this);
                // Ensure google_drive_link is included in the form data
                const googleDriveLink = document.getElementById('edit_google_drive_link')?.value || '';
                formData.set('google_drive_link', googleDriveLink);
                
                const submitButton = this.querySelector('button[type="submit"]');
                const originalHTML = submitButton.innerHTML;
                const form = this;
                
                // Show loading state
                submitButton.disabled = true;
                submitButton.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Updating...';
                
                // Send the update request
                fetch('save_tev_claim.php', {
                    method: 'POST',
                    body: formData
                })
                .then(response => {
                    // First, check if the response is JSON
                    const contentType = response.headers.get('content-type');
                    if (!contentType || !contentType.includes('application/json')) {
                        return response.text().then(text => {
                            console.error('Expected JSON but got:', text);
                            throw new Error('Server returned non-JSON response');
                        });
                    }
                    return response.json().catch(() => {
                        throw new Error('Invalid JSON response from server');
                    });
                })
                .then(data => {
                    if (data.success) {
                        // Show success message
                        showSuccessMessage('TEV claim updated successfully!');
                        // Close the modal
                        const modal = bootstrap.Modal.getInstance(document.getElementById('editTevClaimModal'));
                        if (modal) modal.hide();
                        
                        // Reload the page to reflect changes
                        setTimeout(() => window.location.reload(), 1000);
                        setTimeout(() => {
                            window.location.reload();
                        }, 1500);
                    } else {
                        throw new Error(data.message || 'Failed to update claim');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert('Error: ' + (error.message || 'Failed to update claim'));
                    submitButton.disabled = false;
                    submitButton.innerHTML = originalHTML;
                });
            });
            
            // Handle project change in edit modal
            document.getElementById('edit_project_id')?.addEventListener('change', function() {
                const projectId = this.value;
                const activitySelect = document.getElementById('edit_activity_id');
                const editGoogleDriveLinkInput = document.getElementById('edit_google_drive_link');
                
                // Reset activity select and google drive link
                activitySelect.innerHTML = '<option value="">-- Select Activity --</option>';
                activitySelect.disabled = true;
                if (editGoogleDriveLinkInput) {
                    editGoogleDriveLinkInput.value = '';
                }
                
                // Handle activity selection change in edit modal
                activitySelect.addEventListener('change', function() {
                    handleActivitySelection(this, editGoogleDriveLinkInput);
                });
                
                if (projectId) {
                    // Fetch activities for the selected project
                    fetch(`get_activities.php?project_id=${projectId}`)
                        .then(response => response.json())
                        .then(data => {
                            if (data.success && data.activities.length > 0) {
                                data.activities.forEach(activity => {
                                    const option = document.createElement('option');
                                    option.value = activity.id;
                                    option.textContent = activity.title;
                                    option.dataset.startDate = activity.start_date;
                                    option.dataset.endDate = activity.end_date;
                                    option.dataset.googleDriveLink = activity.google_drive_link || '';
                                    activitySelect.appendChild(option);
                                });
                                activitySelect.disabled = false;
                            } else {
                                activitySelect.innerHTML = '<option value="">No activities found</option>';
                            }
                        })
                        .catch(error => {
                            console.error('Error fetching activities:', error);
                            activitySelect.innerHTML = '<option value="">Error loading activities</option>';
                        });
                }
            });

            // Delete claim with confirmation and loading state - using event delegation
            document.addEventListener('click', function(e) {
                // Check if the clicked element has the delete-claim class or is a child of such an element
                const deleteButton = e.target.closest('.delete-claim');
                if (!deleteButton) return;
                
                e.preventDefault();
                const claimId = deleteButton.getAttribute('data-id');
                if (!claimId) return;
                
                if (confirm('Are you sure you want to delete this TEV claim? This action cannot be undone.')) {
                    // Show loading state
                    const originalHTML = deleteButton.innerHTML;
                    deleteButton.disabled = true;
                    deleteButton.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Deleting...';
                    
                    // Create form data for the delete request
                    const formData = new FormData();
                    formData.append('id', claimId);
                    
                    // Send delete request
                    fetch('delete_tev_claim.php', {
                        method: 'POST',
                        body: formData
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                // Show success message
                                showSuccessMessage('TEV claim deleted successfully');
                                
                                // Remove the deleted row
                                const row = deleteButton.closest('tr');
                                if (row) {
                                    row.style.transition = 'opacity 0.3s';
                                    row.style.opacity = '0';
                                    setTimeout(() => row.remove(), 300);
                                } else {
                                    // If we can't find the row, just reload the page
                                    window.location.reload();
                                }
                            } else {
                                throw new Error(data.message || 'Failed to delete claim');
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                            deleteButton.innerHTML = originalHTML;
                            deleteButton.disabled = false;
                            alert('Error: ' + (error.message || 'Failed to delete TEV claim'));
                        });
                    }
                });
            });

            // Handle search functionality
            const searchInput = document.getElementById('searchInput');
            if (searchInput) {
                searchInput.addEventListener('input', function() {
                    const searchTerm = this.value.toLowerCase();
                    const rows = document.querySelectorAll('tbody tr');
                    let visibleCount = 0;
                    
                    rows.forEach(row => {
                        const text = row.textContent.toLowerCase();
                        if (text.includes(searchTerm)) {
                            row.style.display = '';
                            visibleCount++;
                        } else {
                            row.style.display = 'none';
                        }
                    });
                    
                    document.getElementById('showingCount').textContent = visibleCount;
                });
            }
        });

        // Helper function to get status class
        function getStatusClass(status) {
            if (status.toLowerCase().startsWith('paid')) {
                return 'success';
            }
            
            switch(status.toLowerCase()) {
                case 'under_review': return 'info';
                case 'approved': return 'success';
                case 'rejected': return 'danger';
                case 'paid': return 'success';
                default: return 'secondary';
            }
        }
        
        // Initialize mark as paid functionality
        document.addEventListener('DOMContentLoaded', function() {
            // Initialize mark as paid modals
            const markAsPaidModal = new bootstrap.Modal(document.getElementById('markAsPaidModal'));
            const markAsPaidForm = document.getElementById('markAsPaidForm');
            
            // Set today's date as default in the payment date field
            if (document.getElementById('payment_date')) {
                const today = new Date();
                const formattedDate = today.toISOString().split('T')[0];
                document.getElementById('payment_date').value = formattedDate;
                document.getElementById('payment_date').max = formattedDate; // Prevent future dates
            }
            
            // Handle mark as paid button click
            document.querySelectorAll('.mark-as-paid').forEach(button => {
                button.addEventListener('click', function() {
                    const claimId = this.getAttribute('data-id');
                    const claimAmount = this.getAttribute('data-amount') || '0';
                    
                    document.getElementById('mark_paid_claim_id').value = claimId;
                    
                    // Set the amount in the form
                    const amountInput = document.getElementById('amount');
                    if (amountInput) {
                        amountInput.value = parseFloat(claimAmount).toFixed(2);
                    }
                    
                    markAsPaidModal.show();
                });
            });
            
            // Handle mark as paid form submission
            if (markAsPaidForm) {
                markAsPaidForm.addEventListener('submit', function(e) {
                    e.preventDefault();
                    
                    const form = this;
                    const submitButton = form.querySelector('button[type="submit"]');
                    const spinner = submitButton.querySelector('.spinner-border');
                    const buttonText = submitButton.querySelector('.btn-text');
                    
                    // Show loading state
                    submitButton.disabled = true;
                    spinner.classList.remove('d-none');
                    buttonText.textContent = 'Processing...';
                    
                    // Get form data
                    const formData = new FormData(form);
                    const claimId = formData.get('claim_id');
                    
                    // Send AJAX request
                    fetch('mark_as_paid.php', {
                        method: 'POST',
                        body: formData
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            // Show success message
                            showSuccessMessage('Claim marked as paid successfully!');
                            
                            // Close the modal
                            markAsPaidModal.hide();
                            
                            // Update the status and amount in the table
                            const row = document.querySelector(`tr[data-claim-id="${claimId}"]`);
                            if (row) {
                                // Update status badge
                                const statusBadge = row.querySelector('.badge');
                                if (statusBadge) {
                                    statusBadge.textContent = data.data.status;
                                    statusBadge.className = 'badge badge-success';
                                }
                                
                                // Update amount
                                const amountCell = row.querySelector('.amount');
                                if (amountCell && data.data.amount) {
                                    amountCell.textContent = '₱' + data.data.amount;
                                }
                                
                                // Update the action buttons
                                const actionCell = row.querySelector('.btn-group');
                                if (actionCell) {
                                    // Remove the mark as paid button
                                    const markAsPaidBtn = actionCell.querySelector('.mark-as-paid');
                                    if (markAsPaidBtn) {
                                        markAsPaidBtn.remove();
                                    }
                                }
                            }
                            
                            // Reload the page after a short delay to show the success message
                            setTimeout(() => window.location.reload(), 1000);
                        } else {
                            throw new Error(data.message || 'Failed to mark claim as paid');
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        alert('Error: ' + (error.message || 'Failed to mark claim as paid'));
                    })
                    .finally(() => {
                        // Reset button state
                        submitButton.disabled = false;
                        spinner.classList.add('d-none');
                        buttonText.textContent = 'Mark as Paid';
                    });
                });
            }
        });
    </script>
</body>
</html>
